version: '3.8'

services:
  api:
    build:
      context: ./api
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - ./api/src:/app/src
      - /app/node_modules
    env_file: .env
    environment:
      - NODE_ENV=development
      - DEBUG=text2iac:*
    command: npm run dev
    networks:
      - text2iac-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    ports:
      - "3001:3000"
    volumes:
      - ./frontend/src:/app/src
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - REACT_APP_API_URL=http://localhost:3000
    networks:
      - text2iac-network

  email-bridge:
    build:
      context: ./email-bridge
      dockerfile: Dockerfile.dev
    volumes:
      - ./email-bridge/src:/app/src
    env_file: .env
    environment:
      - PYTHONUNBUFFERED=1
      - FLASK_DEBUG=1
    command: python -m flask run --host=0.0.0.0 --port=5000
    networks:
      - text2iac-network

networks:
  text2iac-network:
    driver: bridge
